[versions]
agp = "8.6.0"
bottomsheets = "3.2.1"
cardview = "1.0.0"
circleimageview = "3.1.0"
constraintlayoutVersion = "2.1.4"
converterGson = "2.9.0"
glide = "4.16.0"
gsonVersion = "2.11.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lifecycleViewmodelKtx = "2.6.1"
loggingInterceptor = "4.12.0"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.2.0"
coreKtx = "1.13.1"
recyclerview = "1.3.2"
firebaseBom = "33.2.0"
playServicesAuth = "21.2.0"
logger = "2.2.0"
gson = "2.11.0"
retrofit = "2.11.0"
rxandroid = "2.1.1"
rxjava = "2.2.21"
rxandroid3 = "3.0.2"
rxjava3 = "3.1.8"
securityCrypto = "1.1.0-alpha06"
kotlin = "2.0.20"
stompprotocolandroid = "1.6.6"
leakcanary = "2.12"

[libraries]
bottomsheets = { module = "com.afollestad.material-dialogs:bottomsheets", version.ref = "bottomsheets" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
constraintlayout-v214 = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
converter-gson-v290 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core = { module = "com.afollestad.material-dialogs:core", version.ref = "bottomsheets" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
logger = { module = "com.orhanobut:logger", version.ref = "logger" }
gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "gson" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
rxandroid = { module = "io.reactivex.rxjava2:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
rxandroid3 = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid3" }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
stompprotocolandroid = { module = "com.github.NaikSoftware:StompProtocolAndroid", version.ref = "stompprotocolandroid" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

